editor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import views_ajax, views_city, views_distance, views_document, views_event, views_klb, views_news, views_user_actions
from .views import views_protocol, views_race, views_region, views_result, views_runner, views_series, views_site, views_social, views_user
from .views import views_klb_race, views_klb_person, views_parkrun, views_mail, views_club, views_klb_team, views_name, views_registration, views_payment
from .views import views_db_structure, views_klb_report, views_util, views_organizer, views_klb_stat, views_age_group_record

app_name = 'editor'

urlpatterns = [
	url(r'^cities/$', views_city.cities, name='cities'),
	url(r'^cities/country/(?P<country_id>[A-Za-z]+)/$', views_city.cities, name='cities'),
	url(r'^cities/region/(?P<region_id>[0-9]+)/$', views_city.cities, name='cities'),

	url(r'^city/(?P<city_id>[0-9]+)/$', views_city.city_details, name='city_details'),
	url(r'^city/(?P<city_id>[0-9]+)/update/$', views_city.city_update, name='city_update'),
	url(r'^city/(?P<city_id>[0-9]+)/delete/$', views_city.city_delete, name='city_delete'),
	url(r'^city/create/$', views_city.city_create, name='city_create'),
	url(r'^city/create/region/(?P<region_id>[0-9]+)/$', views_city.city_create, name='city_create'),
	url(r'^city/(?P<city_id>[0-9]+)/history/$', views_city.city_changes_history, name='city_changes_history'),

	url(r'^cities/list/$', views_ajax.cities_list, name='cities_list'),
	url(r'^cities/list_by_name/$', views_ajax.cities_list_by_name, name='cities_list_by_name'),
	url(r'^klb/participants/list/race/(?P<race_id>[0-9]+)/$', views_ajax.participants_list, name='participants_list'),
	url(r'^klb/unpaid_participants/list/$', views_ajax.unpaid_participants_list, name='unpaid_participants_list'),
	url(r'^race/(?P<race_id>[0-9]+)/results/list/$', views_ajax.race_result_list, name='race_result_list'),
	url(r'^runners/list/$', views_ajax.runners_list, name='runners_list'),
	url(r'^runners/list/runner/(?P<runner_id>[0-9]+)/$', views_ajax.runners_list, name='runners_list'),
	url(r'^runners/list/race/(?P<race_id>[0-9]+)/$', views_ajax.runners_list, name='runners_list'),
	url(r'^organizers/list/$', views_ajax.organizers_list, name='organizers_list'),
	url(r'^organizers/list/organizer/(?P<organizer_id>[0-9]+)/$', views_ajax.organizers_list, name='organizers_list'),
	url(r'^series/list/$', views_ajax.series_list, name='series_list'),
	url(r'^series/list/organizer/(?P<organizer_id>[0-9]+)/$', views_ajax.series_list, name='series_list'),
	url(r'^persons/list/$', views_ajax.persons_list, name='persons_list'),
	url(r'^persons/list/person/(?P<person_id>[0-9]+)/$', views_ajax.persons_list, name='persons_list'),

	url(r'^series/$', views_series.seria, name='seria'),
	url(r'^series/country/(?P<country_id>[A-Za-z]+)/$', views_series.seria, name='seria'),
	url(r'^series/region/(?P<region_id>[0-9]+)/$', views_series.seria, name='seria'),
	url(r'^series/city/(?P<city_id>[0-9]+)/$', views_series.seria, name='seria'),
	url(ur'^series/name/(?P<series_name>[A-Za-zА-Яа-я]+)/$', views_series.seria, name='seria'),
	url(r'^events_wo_protocol/(?P<year>[0-9]+)/$', views_series.events_wo_protocol, name='events_wo_protocol'),
	url(r'^events_wo_protocol_for_klb/(?P<year>[0-9]+)/$', views_series.events_wo_protocol_for_klb, name='events_wo_protocol_for_klb'),
	url(r'^events_not_in_next_year/(?P<year>[0-9]+)/$', views_series.events_not_in_next_year, name='events_not_in_next_year'),
	url(r'^events_wo_statistics/(?P<year>[0-9]+)/$', views_series.events_wo_statistics, name='events_wo_statistics'),
	url(r'^all_events_by_year/regions/(?P<regions>[0-9]+)/$', views_series.all_events_by_year, name='all_events_by_year'),
	url(r'^events_in_seria_by_year/$', views_series.events_in_seria_by_year, name='events_in_seria_by_year'),
	url(r'^events_with_xls_protocol/$', views_series.events_with_xls_protocol, name='events_with_xls_protocol'),
	url(r'^events_in_klb/$', views_series.events_in_klb, name='events_in_klb'),
	url(r'^series_wo_new_event/$', views_series.series_wo_new_event, name='series_wo_new_event'),

	url(r'^series_by_letter/(?P<letter>[^/]+)/$', views_series.series_by_letter, name='series_by_letter'),
	url(r'^series_by_letter/$', views_series.series_by_letter, name='series_by_letter'),

	url(r'^series/(?P<series_id>[0-9]+)/$', views_series.series_details, name='series_details'),
	url(r'^series/(?P<series_id>[0-9]+)/update/$', views_series.series_update, name='series_update'),
	url(r'^series/(?P<series_id>[0-9]+)/delete/$', views_series.series_delete, name='series_delete'),
	url(r'^series/(?P<series_id>[0-9]+)/update_documents/$', views_series.series_documents_update, name='series_documents_update'),

	url(r'^series/create/$', views_series.series_create, name='series_create'),
	url(r'^series/create/series/(?P<series_id>[0-9]+)/$', views_series.series_create, name='series_create'),
	url(r'^series/create/country/(?P<country_id>[A-Za-z]+)/$', views_series.series_create, name='series_create'),
	url(r'^series/create/region/(?P<region_id>[0-9]+)/$', views_series.series_create, name='series_create'),
	url(r'^series/create/city/(?P<city_id>[0-9]+)/$', views_series.series_create, name='series_create'),
	url(r'^series/(?P<series_id>[0-9]+)/history/$', views_series.series_changes_history, name='series_changes_history'),

	url(r'^event/(?P<event_id>[0-9]+)/$', views_event.event_details, name='event_details'),
	url(r'^event/(?P<event_id>[0-9]+)/news/(?P<news_id>[0-9]+)/$', views_event.event_details, name='event_details'),
	url(r'^event/(?P<event_id>[0-9]+)/update/$', views_event.event_update, name='event_update'),
	url(r'^event/(?P<event_id>[0-9]+)/update_distances/$', views_event.event_distances_update, name='event_distances_update'),
	url(r'^event/(?P<event_id>[0-9]+)/update_documents/$', views_event.event_documents_update, name='event_documents_update'),
	url(r'^event/(?P<event_id>[0-9]+)/update_news/$', views_event.event_news_update, name='event_news_update'),
	url(r'^event/(?P<event_id>[0-9]+)/delete/$', views_event.event_delete, name='event_delete'),
	url(r'^event/(?P<event_id>[0-9]+)/change_series/$', views_event.event_change_series, name='event_change_series'),
	url(r'^event/(?P<event_id>[0-9]+)/copy/$', views_event.event_create, name='event_create'),
	url(r'^series/(?P<series_id>[0-9]+)/event/create/$', views_event.event_create, name='event_create'),
	url(r'^event/(?P<event_id>[0-9]+)/history/$', views_event.event_changes_history, name='event_changes_history'),
	url(r'^event/(?P<event_id>[0-9]+)/make_news/$', views_event.event_details_make_news, name='event_details_make_news'),
	url(r'^event/(?P<event_id>[0-9]+)/remove_races_with_no_results/$', views_event.remove_races_with_no_results, name='remove_races_with_no_results'),

	url(r'^refresh_default_calendar/$', views_event.refresh_default_calendar, name='refresh_default_calendar'),
	url(r'^restart/$', views_site.restart, name='restart'),

	url(r'^race/(?P<race_id>[0-9]+)/$', views_race.race_details, name='race_details'),
	url(r'^race/(?P<race_id>[0-9]+)/update/$', views_race.race_update, name='race_update'),
	url(r'^race/(?P<race_id>[0-9]+)/fill_places/$', views_result.race_fill_places, name='race_fill_places'),
	url(r'^race/(?P<race_id>[0-9]+)/swap/(?P<swap_type>[0-9]+)/$', views_result.race_swap_names, name='race_swap_names'),
	url(r'^race/(?P<race_id>[0-9]+)/update_headers/$', views_result.update_race_headers, name='update_race_headers'),
	url(r'^race/(?P<race_id>[0-9]+)/update_stat/$', views_race.race_update_stat, name='race_update_stat'),
	url(r'^race/(?P<race_id>[0-9]+)/reload_parkrun/$', views_parkrun.reload_race_results, name='reload_parkrun_results'),
	url(r'^race/(?P<race_id>[0-9]+)/delete_skipped_parkrun/$', views_parkrun.delete_skipped_parkrun, name='delete_skipped_parkrun'),
	url(r'^race/(?P<race_id>[0-9]+)/add_unoff_result/$', views_race.race_add_unoff_result, name='race_add_unoff_result'),
	url(r'^race/(?P<race_id>[0-9]+)/delete_off_results/$', views_race.race_delete_off_results, name='race_delete_off_results'),

	url(r'^regions/$', views_region.regions, name='regions'),
	url(r'^regions/country/(?P<country_id>[A-Za-z]+)/$', views_region.regions, name='regions'),

	url(r'^distances/$', views_distance.distances, name='distances'),
	url(r'^distance/(?P<distance_id>[0-9]+)/$', views_distance.distance_details, name='distance_details'),
	url(r'^distance/(?P<distance_id>[0-9]+)/update/$', views_distance.distance_update, name='distance_update'),
	url(r'^distance/(?P<distance_id>[0-9]+)/delete/$', views_distance.distance_delete, name='distance_delete'),
	url(r'^distance/(?P<distance_id>[0-9]+)/history/$', views_distance.distance_changes_history, name='distance_changes_history'),

	url(r'^distance/create/$', views_distance.distance_create, name='distance_create'),

	url(r'^dist_splits/$', views_distance.dist_splits, name='dist_splits'),

	url(r'^create_distances_from_dists/$', views_distance.create_distances_from_dists, name='create_distances_from_dists'),

	url(r'^documents/add/$', views_document.add_docs, name='add_docs'),
	url(r'^documents/add_to_old_fields/$', views_document.add_docs_to_old_fields, name='add_docs_to_old_fields'),

	# url(r'^district/(?P<district_id>[0-9]+)/$', views.district_details, name='district_details'),
	# url(r'^district/(?P<district_id>[0-9]+)/update/$', views.district_update, name='district_update'),

	url(r'^result/(?P<result_id>[0-9]+)/$', views_result.result_details, name='result_details'),
	url(r'^result/(?P<result_id>[0-9]+)/update/$', views_result.result_update, name='result_update'),
	url(r'^result/(?P<result_id>[0-9]+)/delete/$', views_result.result_delete, name='result_delete'),
	url(r'^result/(?P<result_id>[0-9]+)/update_splits/$', views_result.result_splits_update, name='result_splits_update'),
	url(r'^result/(?P<result_id>[0-9]+)/klb_add/$', views_result.result_add_to_klb, name='result_klb_add'),

parkrun/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from results.views import views_site
#import probeg_auth.views
from django.conf import settings

urlpatterns = [
	url(r'^about/$', views_site.about, name='about'),
	url(r'^about_new_site/$', views_site.about_new_site, name='about_new_site'),
	url(r'^contacts/$', views_site.contacts, name='contacts'),
	url(r'^protocol/$', views_site.protocol, name='protocol'),
	url(r'^social_links/$', views_site.social_links, name='social_links'),
	url(r'^results_binding/$', views_site.results_binding, name='results_binding'),
	url(r'^how_to_help/$', views_site.how_to_help, name='how_to_help'),
	url(r'^login_problems/$', views_site.login_problems, name='login_problems'),

	# url(r'^best_russian_races_2017/$', views_site.best_russian_races_2017, name='best_russian_races_2017'),
	url(r'^sport_classes/$', views_site.sport_classes, name='sport_classes'),

	url(r'^measurement/$', views_site.measurement_about, name='measurement_about'),

	url(r'^robots\.txt/$', TemplateView.as_view(template_name='misc/robots.txt', content_type='text/plain')),
	url(r'^ads\.txt/$', TemplateView.as_view(template_name='misc/ads.txt', content_type='text/plain')),
	url(r'^favicon.png$', RedirectView.as_view(url='https://probeg.org/dj_static/images/man-square2.png'), name='favicon'),

	url(r'', include('results.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^editor/', include('editor.urls', namespace='editor')),
	# url(r'^', include('django.contrib.auth.urls', namespace='auth')),
	# url(r'', include('social.apps.django_app.urls', namespace='social')),
	url(r'', include('social_django.urls', namespace='social')),
	
	url(r'', include('probeg_auth.urls', namespace='probeg_auth')),
	url(r'^tinymce/', include('tinymce.urls')),
	url(r'', include('starrating.urls', namespace='starrating')),
]

if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		url(r'^__debug__/', include(debug_toolbar.urls)),
   ] + urlpatterns

starrating/urls.py
from django.conf.urls import url

from . import views

app_name = 'starrating'
urlpatterns = [
	url(r'^race/(?P<race_id>[0-9]+)/add_marks/$', views.add_marks, name='add_marks'),
	url(r'^race/(?P<race_id>[0-9]+)/add_marks/user/(?P<user_id>[0-9]+)/$', views.add_marks, name='add_marks_for_user'),

	url(
		r'^race/(?P<race_id>[0-9]+)/test_add_marks/user/(?P<user_id>[0-9]+)/$',
		views.add_marks,
		dict(test_mode=True),
		name='test_add_marks_for_user',
	),

	url(
		r'^race/(?P<race_id>[0-9]+)/add_marks2/user/(?P<user_id>[0-9]+)/$',
		views.add_marks,
		dict(to_move_to_next_race=True),
		name='add_marks2_for_user',
	),

	url(
		r'^race/(?P<race_id>[0-9]+)/abstain/user/(?P<user_id>[0-9]+)/$',
		views.abstain, name='abstain',
	),
	url(
		r'^user/(?P<user_id>[0-9]+)/postpone_rating/$',
		views.postpone_adding_marks, name='postpone_adding_marks',
	),
	url(
		r'^user/(?P<user_id>[0-9]+)/bulk_stop/$',
		views.stop_adding_marks, name='stop_adding_marks',
	),

	url(r'^race/(?P<race_id>[0-9]+)/my_marks/$', views.my_marks, name='my_marks'),

	url(r'^race/(?P<race_id>[0-9]+)/rating/user/(?P<user_id>[0-9]+)/$', views.my_marks, name='my_marks_for_user'),
	url(r'^editor/all_marks/$', views.editor_rating_details, name='editor_rating_details'),
	url(r'^editor/(?P<level>(race|event|series|organizer))/(?P<id_>[0-9]+)/rating/$', views.editor_rating_details, name='editor_rating_details'),
	url(r'^starrating/save_marks/$', views.save_marks, name='save_marks'),
	url(r'^starrating/parameters/$', views.parameters, name='parameters'),
	url(r'^starrating/methods/$', views.methods, name='methods'),
	url(r'^(?P<level>(race|event|series|organizer|root))/(?P<id_>[0-9]+)/rating/$', views.rating_details, name='rating_details'),

	url(r'^group/(?P<group_id>[0-9]+)/delete/$', views.group_delete, name='group_delete'),
]

starrating/templates/abstract_with_tables2.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
	<a href="{% url 'starrating:parameters' %}">Parameters</a> |
	<a href="{% url 'starrating:methods' %}">Methods</a>
	
	<h1>{{ h1 }}</h1>
		{% render_table qs %}
	</body>
</html>

starrating/templates/add_marks.html
{% extends 'results/base.html' %}
{% load results_extras %}
{% load staticfiles %}
{% block main %}
<div class="row"> <!-- Header -->
	<div class="col-md-6">
		<h3><a href="{{ event.get_absolute_url }}">{{ event|safe }}</a>,
			{{ event.dateFull|safe }}
		</h3>
	</div>
	<div class="col-md-6 text-right">
		{% include 'results/event_edit_buttons.html' %}
	</div>
</div>
{% include 'results/event_details_row.html' with race_page=1 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.stars {
	color: lightgray;
}
.c1 {
	display: none;
}
.fa-times {
	 color: lightgrey;
}
</style>


<div class="row"><div class="col-md-8 col-md-offset-1 col-sm-12 col-sm-offset-0">
	{% if to_move_to_next_race %}
		<div class="row">
			<div class="col-md-4">
				<a href="{% url 'starrating:abstain' race.id for_user.id %}">
					 <button type="button" class="btn btn-sm btn-warning">Не хочу оценивать этот забег</button>
				</a>
			</div>
			<div class="col-md-4 text-center">
				<a href="{% url 'starrating:postpone_adding_marks' for_user.id %}">
					 <button type="button" class="btn btn-sm btn-warning">Отложить оценки забегов на неделю</button>
				</a>
			</div>
			<div class="col-md-4 text-right">
				<a href="{% url 'starrating:stop_adding_marks' for_user.id %}">
					 <button type="button" class="btn btn-sm btn-warning">Больше не предлагать оценивать забеги</button>
				</a>
			</div>
		</div>
		<br/>
	{% endif %}

	<h3>Пожалуйста, оцените забег на дистанции {{ race.get_precise_name }}
		{% if not for_current_user %}за пользователя {{ for_user.get_full_name }}{% endif %}
		по следующим параметрам:
	</h3>

	<p>Необязательно ставить оценки по всем параметрам; если о чём-то у вас не осталось никаких впечатлений, можно ничего не ставить (для этого нажмите на крестик слева от звёздочек).
	<br/>
	<strong>Отзыв тоже писать необязательно, но лучше напишите хоть пару слов: это очень поможет будущим участникам!</strong></p>

	<p id="no_js" style="color: red">
	У вас отключен Javascript. Для простановки оценок необходимо включить Javascript в настройках браузера.
	</p>

	<form action="{% url 'starrating:save_marks' %}" id="rating_form" method="post">
		{% csrf_token %}

		{% for par in parameters %}
			<hr/>
			<div class="row">
				<div class="col-md-6">
					<h4>{{ par.name }}</h4>
					{{ par.description|linebreaks  }}
				</div>
				<div class="col-md-6">
					<span class="stars" id="td{{ par.id }}">
						{% for n in values %}
							<input class="c1" type="radio" id="q{{ par.id }}r{{ n }}" name="q{{ par.id }}" value="{{ n }}"{% if n == -1 %} checked="checked"{% endif %} >
							{% if n != -1 %}
								<label id="q{{ par.id }}l{{ n }}" for="q{{ par.id }}r{{ n }}" onclick="clicked({{ par.id }}, {{ n }})">
									<i id="i{{ par.id }}r{{ n }}" class="fa {% if n == 0 %}fa-times{% else %}fa-star-o{% endif %}"></i>
								</label>
							{% endif %}
							&nbsp;{% if n == 0 %}&nbsp;{% endif %}
						{% endfor %}
					</span>&nbsp;<span id="descr{{ par.id }}">Поставьте оценку или нажмите крестик</span>
				</div>
			</div>
		<!-- <tr>
			<td>
				{{ par.id }}. {{ par.name }}:
			</td>
			<td class="stars" id="td{{ par.id }}">
				 {% for n in values %}
				<input class="c1" type="radio" id="q{{ par.id }}r{{ n }}" name="q{{ par.id }}" value="{{ n }}"{% if n == -1 %} checked="checked"{% endif %} >
				{% if n != -1 %}
				<label id="q{{ par.id }}l{{ n }}" for="q{{ par.id }}r{{ n }}" onclick="clicked({{ par.id }}, {{ n }})">
					<i id="i{{ par.id }}r{{ n }}" class="fa {% if n == 0 %}fa-times{% else %}fa-star-o{% endif %}"></i>
				</label>
				{% endif %}
				{% if n == 0 %}&nbsp;{% endif %}
				{% endfor %}
			</td>
			<td id="descr{{ par.id }}">
			&nbsp;Поставьте оценку или нажмите крестик
			</td>
		</tr> -->
		{% endfor %}

		<input type="hidden" name="race_id" value="{{ race.id }}">
		<input type="hidden" name="for_user" value="{{ for_user.id }}">
		<input type="hidden" name="for_current_user" value="{{ for_current_user }}">
		{% if to_move_to_next_race %}<input type="hidden" name="to_move_to_next_race" value="1">{% endif %}
		{% if test_mode %}<input type="hidden" name="test_mode" value="1">{% endif %}

		<br/><br/>
		<h4>Отзыв (необязательно):</h4>
		<p>Особенно кстати будет отзыв, если по каким-то параметрам вы поставили низкие оценки; его смогут и учесть участники, и организаторы будущих забегов серии.</p>
		<textarea id="review" onchange="control_checkbox_state()" onpaste="control_checkbox_state()" onkeyup="control_checkbox_state()" rows="5" form="rating_form" name="review" class="form-control"></textarea>

		<input type="checkbox" onmouseover="control_checkbox_state()" onfocus="control_checkbox_state()" name="show_my_name" id="id_show_my_name" value="1" disabled>&nbsp;&nbsp;<label for="id_show_my_name" onmouseover="control_checkbox_state()">Отображать ваше имя рядом с вашим отзывом</label>
		<br/><br/>
		<input id="submit" type="submit" value="Отправить оценки и отзыв" class="btn btn-success" {% if not test_mode %}disabled {% endif %}/>
	</form>

	<p id="debug"></p>

	<script>
		document.getElementById("no_js").innerHTML = "";

		var descr = ["{{ RATING_VALUES_DESCRIPTIONS|join:'", "' }}"]

		var checked = {
			 {% for par in parameters %}
			 p{{ par.id }} : 0{% if not forloop.last %},{% endif %}
			 {% endfor %}
		}
		n_to_check = {{ parameters|length }}

	 checkbox_was_checked = false;
	 control_checkbox_state();

	 function change_colors(question_no, star_no) {
		 console.log("ch_col " + question_no + " " + star_no)
		 if (star_no == 0) {
				document.getElementById("td" + question_no).style.color = "lightgray";
		 }
		 else {
				document.getElementById("td" + question_no).style.color = "orange";
		 }
		 for (i = 1; i <= star_no; i++) {
				document.getElementById("q" + question_no + "l" + i).innerHTML = '<i class="fa fa-star">';
		 }
		 for (; i <= 5; i++) {
				document.getElementById("q" + question_no + "l" + i).innerHTML = '<i class="fa fa-star-o">';
		 }
		 document.getElementById("descr" + question_no).innerHTML = "— " + descr[star_no];
		 if (star_no == 0) {
				 document.getElementById("i" + question_no + "r0").style.color = "black";
		 } else {
				 document.getElementById("i" + question_no + "r0").style.color = "lightgrey";
		 }


	 }

	 function clicked(question_no, star_no) {
			console.log("clicked " + question_no + " " + star_no);
			if (checked["p" + question_no] == 0) {
					console.log("clicked-if");
					checked["p" + question_no] = 1;
					n_to_check--;
					console.log("n_to_check = " + n_to_check);
					if (n_to_check == 0) {
							 document.getElementById("submit").disabled = false;
					}
			}
			change_colors(question_no, star_no);
			// document.getElementById("submit").disabled = false;
	 }

	 function control_checkbox_state() {
			 if (document.getElementById("review").value.trim() == '') {
					if (! document.getElementById("id_show_my_name").disabled) {
						checkbox_was_checked = document.getElementById("id_show_my_name").checked;
						document.getElementById("id_show_my_name").checked = false;
						document.getElementById("id_show_my_name").disabled = true;
//						document.getElementById("debug").innerHTML += 'O';
					}
//					else document.getElementById("debug").innerHTML += 'o';

			 } else {
					if (document.getElementById("id_show_my_name").disabled) {
						 document.getElementById("id_show_my_name").disabled = false;
						 document.getElementById("id_show_my_name").checked = checkbox_was_checked;
//						 document.getElementById("debug").innerHTML += 'X';
					}
//					else document.getElementById("debug").innerHTML += 'x';
			 }
	 }

	 {% for par in parameters %}
//	 document.getElementById("q{{ par.id }}r0").checked = true;
//	 document.getElementById("descr{{ par.id }}").innerHTML = "- " + descr[0];
	 {% endfor %}

	</script>
</div></div>
{% endblock %}

starrating/templates/methods.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>Method model</title>
    </head>
    <body>
        {% render_table methods %}
    </body>
</html>

starrating/templates/my_marks.html
<html>
<body>

{% url 'starrating:rating_details' level='group' id_=group_id as rating_details_url %}

<p>
Альтернативный формат:
<a href="{{  rating_details_url }}">
         {{  rating_details_url }}
</a>
</p>

{% if marks %}
<ul>
{% for mark in marks %}
<li>{{ mark.id }}. par={{ mark.parameter_id }} value={{ mark.value }}</li>
{% endfor %}
</ul>
{% else %}
<p>Нет оценок</p>
{% endif %}

{% if review %}
<p>Отзыв:</p>
<textarea readonly>{{ review.content }}</textarea>
<p>Показывать ли имя пользователя рядом с отзывом: {{ review.show_user_name }}.

	{% if review.response %}
	<p>Ответ:</p>
	<textarea readonly>{{ review.response }}</textarea>
	{% endif %}

{% endif %}

</body>
</html>

starrating/templates/parameters.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>Parameter model</title>
    </head>
    <body>
        {% render_table parameters %}
    </body>
</html>

starrating/templates/save_marks.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"> 
</head>
<body>
<p>save_marks page</p>
<pre>
{{ debug_out }}
</pre>

</body>
</html>

starrating/templates/save_marks_error.html
{% extends 'results/base.html' %}
{% load results_extras %}
{% load staticfiles %}
{% load starrating %}
{% block main %}

<div class="row"><div class="col-md-8 col-md-offset-1 col-sm-12 col-sm-offset-0">

<h3>
Извините, что-то пошло не так и ваши оценки не записались.
Пожалуйста, вернитесь на предыдущую страницу и повторите.
</h3>
<h3>Обратите внимание на 
{% if param_names|length == 1 %}
позицию
{% else %}
следующие позиции:
{% endif %}
"{{ param_names|join:'", "' }}"
</h3>
<p>Иногда помогает изменить оценку на любую другую и сразу вернуть прежнюю,
которую вы реально хотите поставить</p>

<button onclick="window.history.back()">Вернуться</button>

{% endblock %}